### ISSUE TITLE
При падающей сборке проходят автоматические тесты по авторизации пользователей банковского приложения

### ISSUE THREAD

**Issue by Yoliker** [Yoliker/SQLdz8#1]
# Описание
При использовании команды gradlew clean test падает сборка автоматических тестов по авторизации пользователей банковского приложения, а при запуске тестов после этого командой Run Test сборка успешна

# Локация дефекта
![падение сборки](https://github.com/user-attachments/assets/57dd7426-517d-422b-a371-8ccd8b748dc7)

# Шаги воспроизведения
1. Открыть в IdeaProject папку с автотестами SQLdz8.
2. Запустить в терминале контейнер командой docker compose up.
3. Запустить на другой странице терминала команду java -jar ./artifacts/app-deadline.jar.
4. Открыть приложение DBeaver и создать базу данных через команду Новое соединение/MySQL и заполнение полей  данными из файла docker-compose.yml.
5. Запустить сборку в терминале командой ./gradlew clean test "Ddb.url=jdbc:mysql://localhost:3306/app".
6. Запустить в классе LoginBankTest тесты командой Run Test.

*Ожидаемый результат:* После запуска сборки командой ./gradlew clean test "Ddb.url=jdbc:mysql://localhost:3306/app" появляется приложение банка http://localhost:9999, все тесты успешно проходят и в терминале появляется запись Build Successful. После запуска в классе LoginBankTest тестов командой Run Test появляется приложение банка http://localhost:9999, все тесты успешно проходят и в терминале появляется запись Build Successful.
*Фактический результат:* После запуска сборки командой ./gradlew clean test "Ddb.url=jdbc:mysql://localhost:3306/app" в терминале появляется запись  Build failed with an exception, а после этого при запуске в классе LoginBankTest тестов командой Run Test появляется приложение банка http://localhost:9999, все тесты успешно проходят и в терминале появляется запись Build Successful.

# Скриншот
*после запуска тестов командой Run Test*
![тест проходит при падающей сборке](https://github.com/user-attachments/assets/7f83fe1e-ffdf-450e-a028-a25399fd6bc7)

*результаты запуска тестов в автоматическом режиме*
![Test results - LoginBankTest](https://github.com/user-attachments/assets/a93351f0-0323-4706-ba1c-8e4a5a63ff36)

# Окружение
* **Операционная система:** Windows 10 Pro версия 22H2, сборка 19045.5247
*  **IntelliJ IDEA:** Communiti Edition 2024.2.0.1
*  **JAVA:** OpenJDK 11
* **Приложение DBeaver** версия 24.3.1

**Comment by andrew-pahomov** [comment]
Фактический результат на скриншоте противоречит описанному в issue фактическому результату. Issue некорректно, фактический результат не подтвержден.
