### ISSUE TITLE
После очистки таблиц базы данных в приложении DBeaver не обновляются таблицы auth_codes и card_transaction

### ISSUE THREAD

**Issue by Yoliker** [Yoliker/SQLdz8#2]
# Описание
При подготовке lдля автоматических тестов базы данных app в приложении DBeaver не появляются при обновлении данные в таблицах  auth_codes и card_transaction

# Локация дефекта
![не появляются коды авторизации при обновлении таблицы](https://github.com/user-attachments/assets/f986fcd8-b1d4-40fd-a843-229c059e3fe8)

# Шаги воспроизведения
1. Открыть в IdeaProject папку с автотестами SQLdz8.
2. Запустить в терминале контейнер командой docker compose up.
3. Запустить на другой странице терминала команду java -jar ./artifacts/app-deadline.jar.
4. Открыть приложение DBeaver и создать базу данных через команду Новое соединение/MySQL и заполнение полей  данными из файла docker-compose.yml. 
5. Открыть 4 таблицы базы данных app - во всех 4х таблицах отображаются данные пользователей.
6. Запустить сборку в терминале командой ./gradlew clean test "Ddb.url=jdbc:mysql://localhost:3306/app" или запустить в классе LoginBankTest тесты командой Run Test.
7. Остановить джарник командой Ctrl+C.
8. Очистить данные 4х таблиц в приложении DBeaver в OpenSQL console командами DELETE FROM название таблицы + нажать кнопку Выполнить при удалении данных из каждой таблицы.
9. Закрыть таблицы и нажать F5 или кнопку Обновить в нижней части приложения.
10. Заново открыть таблицы базы данных.

*Ожидаемый результат:* После обновления в 4х таблицах появляются данные зарегистрированных пользователей и их карт.
*Фактический результат:* После обновления в таблицах user  и cards появляются данные зарегистрированных пользователей и их карт. Остаются пустыми таблицы auth_codes и card_transaction. 
(Остановка джарника и новый запуск его, закрытие и открытие приложения DBeaver не помогли решить проблему. Джарник запускается, таблицы auth_codes и card_transaction не обновляются)

# Окружение
* **Операционная система:** Windows 10 Pro версия 22H2, сборка 19045.5247
*  **IntelliJ IDEA:** Communiti Edition 2024.2.0.1
*  **JAVA:** OpenJDK 11
* **Приложение DBeaver** версия 24.3.1

**Comment by andrew-pahomov** [comment]
Ожидаемый результат совсем непонятен. Вы на 8 шаге очистили таблицы, откуда в таком случае должны появиться в них данные? Данные в таблицы пишет джарник.
